<?php
/**
 * Copyright (C) Web-Studio.cv.ua
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * <info@web-studio.cv.ua>, 2018
 */

namespace wscvua\yii2_blockio_dogecoin\widgets;

use yii\base\Widget;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class AddressWidget extends Widget
{
    public $address;
    public $path = '//dogechain.info/address/';
    public $options = [
        'style' => 'font-family: Monospace'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        echo Html::a($this->address, $this->path . $this->address, ArrayHelper::merge($this->options, [
            'target' => '_blank'
        ]));
    }
}