<?php

namespace wscvua\yii2_blockio_dogecoin\widgets;

use yii\base\Widget;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class TxWidget extends Widget
{
    public $tx;
    public $maxLength = 10;
    public $path = '//dogechain.info/tx/';
    public $options = [
        'style' => 'font-family: Monospace'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $text = substr($this->tx, 0, $this->maxLength) . '...';
        $html = Html::a($text, $this->path . $this->tx, ArrayHelper::merge($this->options, [
            'target' => '_blank'
        ]));
        echo $html;
    }
}